### ISSUE TITLE
Delete `.git` folder from all project selections

### ISSUE THREAD

**Issue by keonik** [MileTwo/create-m2-app#24]
Right now the `.git` folder is only deleted for Mile Two developer projects. Recommend deleting for all projects so the open-source community doesn't actually get commits from template projects

**Comment by heystevegray** [comment]
As of 06/25/2021 this fails even as a mile two developer, if you do not deploy to gitlab.

> I noticed if I do not add to mile2 gitlab the generated project retains the original remote URL.

```bash
$ git remote get-url origin
https://github.com/MileTwo/nextjs-typescript-material-ui-eslint-jest.git
```
